
spring:
  application:
    name: spring-rabbit
  rabbitmq:
    passport-knock-door:
        exchangeName: direct.exchange.test
        exchangeType: direct
        routingKey: orig_2
    addresses: 127.0.0.1:5671,127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /
  rabbitmq1:
      addresses: 192.168.1.2:5672
      username: guest
      password: guest
      virtual-host: /
      host: 127.0.0.1
