---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liqiuwei.
--- DateTime: 2019/6/22 17:12
---
local ngx_var = ngx.var
local ngx_log = ngx.log
local debug = ngx.DEBUG

ngx_log.log(debug,"body:",ngx.var.resp_body)