package com.thc.rules;
import java.math.BigDecimal;
dialect  "mvel"

/**
在解析declare后，会使用ASM生成定义类型的字节码，最终得到相应的Class实例。最终翻译为java类
*/
 declare  OrderFact
  age:int
  price:BigDecimal
   @author("liqiuwei")//定义元数据，自定义的元数据可以被理解为类型的描述信息。对规则引擎的工作并不会产生影响
 end

rule "BaseRule"
    when
    eval(true)
    then
    OrderFact orderFact=new OrderFact();
    orderFact.setAge(30);
    System.out.println("fact age::"+orderFact.getPrice());
end