package com.ms.rules;
import  com.ms.bean.User
import com.ms.util.RedisUtil;

 no-loop


declare UserFact
     id:long;
     age:int;
     valid:boolean;
 end
/**
对规则引擎的工作并不会产生影响，除了可以使用在规则文件中定义的函数外，还可以在规则或者在函数中使用Java类的静态方法
*/
function  int getAge(String key){
  return Integer.valueOf(RedisUtil.getRu().get(key));
}
/**
定义通用的业务逻辑
*/
function boolean canUse(Long id){
    if(id!=null){
      return true;
    }
  return false;
}

rule "init UserInfo"
    when
      $u : User(canUse(id));
    then
      UserFact userFact=new UserFact();
      userFact.setAge(getAge("user:"+$u.getId()));
      System.out.println("age=="+userFact.getAge());
      insert(userFact);
end

rule "less than 17"
  when
    $uf: UserFact(age<17)
     $u:User(id!=null)
  then
   System.out.println("age "+$uf.getAge()+" less than 17");
    $u.setName("lisi"+17);
end

rule "more than 20"
  when
    $uf: UserFact(age>10)
     $u:User(id!=null)
  then
   System.out.println("age "+$uf.getAge()+" more than 20");
    $u.setName("lisi"+20);
end






