spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      username: admin
      password: admin
server:
  port: 8443
  compression:
    enabled: true
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:keystore.p12 # \u542F\u7528http2
    key-store-password: 123456 # \u8BC1\u4E66\u5BC6\u7801
    key-store-type: PKCS12 # \u8BC1\u4E66\u7C7B\u578B
    protocol: TLSv1.2 # \u534F\u8BAE\u7C7B\u578B
    key-alias: undertow


